apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dashappresources.dash.app  # The name should be <plural>.<group>
spec:
  group: dash.app
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              foo:
                type: string
              bar:
                type: integer
    subresources:
      status: {}
  scope: Namespaced  # Can be "Namespaced" or "Cluster"
  names:
    plural: dashappresources
    singular: dashappresource
    kind: DashAppResource
    shortNames:
    - dar