apiVersion: batch/v1
kind: Job
metadata:
  name: dashapp-job
spec:
  template:
    spec:
      # node selector
      # nodeSelector:
      #   role: jobrunner

      # direct scheduling
      # nodeName: node1

      # agnostic scheduling
      # resources:
      #   requests:
      #     memory: "64Mi"
      #     cpu: "250m"  # 25% CPU
      #   limits:
      #     memory: "128Mi"
      #     cpu: "500m"  # 50% CPU
      
      # pod tolerations
      # tolerations:
      #   - key: "role"
      #     operator: "Equal"
      #     value: "jobrunner"
      #     effect: "NoSchedule" # "NoExecute"

      # node & pod affinities/antiaffinites
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: disktype
      #           operator: In
      #           values:
      #           - ssd
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 1
      #       preference:
      #         matchExpressions:
      #         - key: zone
      #           operator: In
      #           values:
      #           - us-east-1a
      #   podAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchLabels:
      #           app: frontend
      #       topologyKey: kubernetes.io/hostname
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchLabels:
      #           app: frontend
      #       topologyKey: kubernetes.io/hostname

      containers:
      - name: dashapp
        image: pythondashapp:v0
        command: ["python3"]  # Override the entrypoint
        args: ["/app/src/job.py"]
        volumeMounts:
        - name: config-yaml-volume
          mountPath: /app/config/config.yaml
          subPath: config.yaml
        - name: dashapp-data-volume
          mountPath: /app/data
        env:
        - name: DASH_APP_CONFIG
          valueFrom:
            secretKeyRef:
              name: dashapp-secret
              key: DASH_APP_CONFIG
        - name: DASH_APP_OWNER
          valueFrom:
            secretKeyRef:
              name: dashapp-secret
              key: DASH_APP_OWNER
      volumes:
      - name: config-yaml-volume
        configMap:
          name: dashapp-config
      - name: dashapp-data-volume
        persistentVolumeClaim:
          claimName: dashapp-pvc
      restartPolicy: OnFailure