apiVersion: v1
kind: Service
metadata:
  name: dashapp-service
  # `minikube service dashapp-service` to see app through service
spec:
  type: NodePort
  selector:
    app: dashapp
  ports:
    - protocol: TCP
      port: 8050
      targetPort: 8050
      nodePort: 30001


